"""Add round_number and dealer_seat_index to tables

Revision ID: 73a12a5a739b
Revises: 
Create Date: 2026-04-13 18:13:44.312071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '73a12a5a739b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('round_number', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('tables', sa.Column('dealer_seat_index', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'dealer_seat_index')
    op.drop_column('tables', 'round_number')
    # ### end Alembic commands ###
