"""add tournament_blind_multiplier to tables

Revision ID: 9dc0d4e684ac
Revises: 73a12a5a739b
Create Date: 2026-04-16 16:14:57.319303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9dc0d4e684ac'
down_revision: Union[str, None] = '73a12a5a739b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('tournament_blind_multiplier', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'tournament_blind_multiplier')
    # ### end Alembic commands ###
